### ISSUE TITLE
ui: guide user to page where B2SHARE API token can be set (and obtained)

### ISSUE THREAD

**Issue by hjhsalo** [EUDAT-B2DROP/b2sharebridge#48]
When B2SHARE API token has not been set, b2sharebridge displays an error text _'Please set B2SHARE API token'_. It might not be clear where this token should be set.

Maybe the text could be changed to _'Please set B2SHARE API token here'_, where ___'here'___ points to settings page of B2DROP, to section _'EUDAT B2SHARE Bridge'_, if possible.

On B2DROP settings page, it might be good to say that token can be obtained from B2SHARE. Maybe a link to user's profile page at B2SHARE (e.g. https://b2share.eudat.eu/user)?

![token_not_set](https://user-images.githubusercontent.com/9445833/41956285-c3925230-79eb-11e8-8a4f-b61a959dfc45.png)

**Comment by apw1388** [comment]
A link to obtain the token is difficult, if we support multiple B2SHARE servers. We will stall the link for obtain a token at the moment.

**Comment by mwinkens** [comment]
As of 2023 this is now possible, since we support custom configuration of multiple instances. This would cause a major update, since we would add a column and the admin has to configure it once. I wouldn't directly link to it in the sidebar, but at the settings for each instance. A direct link to the settings is already established.

**Comment by mwinkens** [comment]
- Now trying to submit to b2share without token links to the settings page
- Now each server in the settings links to the b2share-sever, where you can obtain the token

closed by #82
